version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "12345678"
  web:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      PORT: "4000"
      PGHOST: "db"
      PGUSER: "postgres"
      PGDBNAME: "heating"
      PGPASSWORD: "12345678"
    depends_on:
      - db
